/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menuatm;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author rama_
 */
public class atm extends javax.swing.JFrame {
    double hasil;
    String name3, name;
    double saldo, norek;
    double masukan;
    /**
     * Creates new form atm
     */
    public atm(String name) {
        initComponents();
        outputname.setText("Mr."+name);
        this.name = name3;
    }
    /**
     *
     * @param saldo
     */
    public atm(int saldo) {
    this.saldo = saldo;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JLabel();
        z = new javax.swing.JButton();
        setoruang = new javax.swing.JButton();
        transfer = new javax.swing.JButton();
        ambiluang = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        atm = new javax.swing.JLabel();
        outputname = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        menu.setText("Silahkan pilih menu di bawah ini");

        z.setText("Cek Saldo");
        z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zActionPerformed(evt);
            }
        });

        setoruang.setText("Setor Uang");
        setoruang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setoruangActionPerformed(evt);
            }
        });

        transfer.setText("Transfer");
        transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferActionPerformed(evt);
            }
        });

        ambiluang.setText("Ambil Uang");
        ambiluang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ambiluangActionPerformed(evt);
            }
        });

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        atm.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        atm.setText("ATM BANK DIPO");

        outputname.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(outputname, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(transfer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(z, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                            .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(135, 216, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(setoruang, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ambiluang, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(atm, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(atm, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(outputname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(z, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setoruang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ambiluang, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zActionPerformed
       //simpanAwal();
        JOptionPane.showMessageDialog(rootPane, "Saldo Anda Saat Ini adalah : Rp"+ saldo);
        hasil = saldo;
        saldo = hasil;
    }//GEN-LAST:event_zActionPerformed

    private void setoruangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setoruangActionPerformed
        // TODO add your handling code here
        try{
            masukan = Double.parseDouble(JOptionPane.showInputDialog("Masukkan Jumlah Nominal : "));
            if (masukan <0){
                JOptionPane.showMessageDialog(rootPane, "Input Salah");
            }
            else{
                JOptionPane.showMessageDialog(rootPane,"Saldo Anda Saat Ini adalah : Rp"+ (saldo + masukan));
                hasil = saldo + masukan;
                saldo = hasil;
            }
        }catch(HeadlessException | NullPointerException | NumberFormatException a){
            JOptionPane.showMessageDialog(rootPane, "Input Salah");
         }
    }//GEN-LAST:event_setoruangActionPerformed

    private void transferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferActionPerformed
        try{
            name3 = JOptionPane.showInputDialog("Silahkan Masukkan Nama ");
            String patern = "^[a-zA-Z]*$";
        if(!name3.matches(patern)){
            JOptionPane.showMessageDialog(null, "Maaf Input Salah");
        }else{
            try{    
              norek = Double.parseDouble(JOptionPane.showInputDialog("Masukkan No.Rek : "));
            if (norek < 0){
              JOptionPane.showMessageDialog(rootPane, "Input Salah");
            }else if (norek > 0){
              masukan = Double.parseDouble(JOptionPane.showInputDialog("Masukkan Jumlah Nominal : "));
                if (masukan < 0){
                    JOptionPane.showMessageDialog(rootPane, "Input Salah");
                }else if (masukan > 0){
                    if (saldo <= masukan){
                        JOptionPane.showMessageDialog(rootPane,"Maaf Saldo Anda Kurang !");
                        JOptionPane.showMessageDialog(rootPane,"Tambahkan Saldo Rekening Anda Terlebih Dahulu");
                    }else if (saldo >= masukan){
                        hasil = saldo - masukan;
                        saldo = hasil;
                        JOptionPane.showMessageDialog(rootPane,"Saldo Anda Saat Ini adalah : Rp"+ saldo+ "\n"+" Berhasil transfer kepada "+name3+"\n"+" Ke No.Rek : "+norek+"\n"+" Sebesar : Rp"+ masukan);
                    }
                }
            }
            }catch(NullPointerException h){
                JOptionPane.showMessageDialog(rootPane, "Input Salah");
            }
        }
       }catch(HeadlessException |NullPointerException| NumberFormatException d){
            JOptionPane.showMessageDialog(rootPane, "Input Salah");      
        }
    }//GEN-LAST:event_transferActionPerformed

    private void ambiluangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ambiluangActionPerformed
        // TODO add your handling code here:
        try{
            masukan = Double.parseDouble(JOptionPane.showInputDialog("Masukkan Jumlah Nominal : "));
        if(masukan < 0){
            JOptionPane.showMessageDialog(rootPane, "Input Salah");
        }else if (masukan > 0){
            if (saldo <= masukan){
                JOptionPane.showMessageDialog(rootPane,"Maaf Saldo Anda Kurang !");
                JOptionPane.showMessageDialog(rootPane,"Tambahkan Saldo Rekening Anda Terlebih Dahulu");
            }else if (saldo >= masukan){
                hasil = saldo - masukan;
                saldo = hasil;
                JOptionPane.showMessageDialog(rootPane,"Saldo Anda Saat Ini adalah : Rp"+ hasil+ "\n");
            }
         }
        }catch(HeadlessException | NullPointerException | NumberFormatException b){
            JOptionPane.showMessageDialog(rootPane, "Input Salah"); 
        }
    }//GEN-LAST:event_ambiluangActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(atm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(atm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(atm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(atm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ambiluang;
    private javax.swing.JLabel atm;
    private javax.swing.JButton exit;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel outputname;
    private javax.swing.JButton setoruang;
    private javax.swing.JButton transfer;
    private javax.swing.JButton z;
    // End of variables declaration//GEN-END:variables
}
